# Generated by Django 3.1.1 on 2020-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20200927_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_uuid', models.SlugField(blank=True)),
                ('caller1', models.SlugField(blank=True, max_length=8)),
                ('caller2', models.SlugField(blank=True, max_length=8)),
                ('validation_token', models.SlugField(blank=True, max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
