# Generated by Django 3.1.1 on 2020-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_validroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='validroom',
            name='validation_username',
            field=models.SlugField(blank=True, max_length=32),
        ),
    ]
