# Generated by Django 3.1.1 on 2020-09-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20200930_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validroom',
            name='validation_username',
            field=models.SlugField(blank=True),
        ),
    ]
