# Generated by Django 3.1.1 on 2020-10-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20200930_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller1', models.SlugField(blank=True, max_length=8)),
                ('caller2', models.SlugField(blank=True, max_length=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
